services:
  - type: web
    name: quote-pdf-generator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
